version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: useradminquery
      POSTGRES_DB: dma_java
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: